# This will be the first part of the title tag for your site <title> site.name + page.title </title>
name: "☠☣"
# Populates the meta description for the site. Should be under 150 characters for best SEO purposes.
descripiton: "Thoughts on vim, css, design, and software-development."

# Owner (organization or individual) of site content
author: "mrmrs"

#url: "[http:// ]"
url: "http://xn--h4hg.ws"
#url: "localhost:4000"

port: 3000

exclude: [node_modules]
# Pagination variable for how many posts to show in a list
paginate: 10

# Style of permalinks
permalink: pretty

# Variable format options for URL styles below
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-month:day-:year/:title.html/            => 04-29-2009/slap-chop.html
# /blog/:yearr/:month/:day/:title                 => /blog/2009/04/29/slap-chop/index.html

# UnComment once you have pygments installed. Used for code syntax highlighting.
highlighter: pygments
#

future: false
